<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>dq</string>
   </array>
  <key>name</key>
  <string>discordquery</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.discordquery</string>
  <key>uuid</key>
  <string>b6159f77-e481-495b-8faa-9f7e9509d697;</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([uU][sS][eE])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([lL][iI][sS][tT][eE][nN])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([iI][nN][cC][lL][uU][dD][eE])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([eE][xX][cC][lL][uU][dD][eE])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([fF][eE][tT][cC][hH])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([rR][eE][aA][dD])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([lL][iI][mM][iI][tT])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([bB][eE][fF][oO][rR][eE])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([aA][fF][tT][eE][rR])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([aA][rR][oO][uU][nN][dD])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([dD][eE][lL][eE][tT][eE])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([sS][eE][nN][dD])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([iI][nN])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([eE][dD][iI][tT])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([wW][iI][tT][hH])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([sS][hH][oO][wW])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([pP][rR][eE][sS][eE][nN][cC][eE])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([rR][aA][wW])</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(t)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(g)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(c)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(m)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(u)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(A)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(E)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(M)</string>
          <key>name</key>
          <string>keyword.discordquery</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(:)</string>
          <key>name</key>
          <string>punctuation.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.discordquery</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.discordquery</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.discordquery</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.discordquery</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.discordquery</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.discordquery</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.discordquery</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
